### ISSUE TITLE
demo/hello.js 编译 字节码后，通过loader执行没有任何输出

### ISSUE THREAD

**Issue by iamluodong** [Nihiue/little-byte-demo#1]
非常感谢，这个项目对我帮助很大，之前一直用的pkg方案，我看您有计划讲讲这部分，非常期待啊。
例子hello-export.js 测试成功，hello.js 一直没有输出，下面是我的测试方法。
1. 编译字节码
node lib/compile.js demo/hello.js
2. 执行字节码
node lib/loader.js demo/hello.bytecode

无任何输出。

**Comment by iamluodong** [comment]
找到问题了，compile.js 里，是封装完成后，生成的字节码，导致执行没有任何输出。
 const code = await fs.readFile(filePath, 'utf-8');
  const wrappedCode = _module.wrap(code);
  const script = new vm.Script(wrappedCode);

**Comment by Nihiue** [comment]
对，默认都是按照CommonJS的模块去打包的，所以会有wrap代码，生产环境使用建议看一下https://www.npmjs.com/package/bytenode 这个库，提供了 compileAsModule 的参数
