### ISSUE TITLE
引入某些第三方包，会导致执行错误

### ISSUE THREAD

**Issue by iamluodong** [Nihiue/little-byte-demo#2]
通过webpack打包，对于某些第三方库，编译成字节码后，会报告 ReferenceError: require is not defined 错误
目前测试有问题的包：
fs-extra  
source-map-support 
这两个包只要引入任意一个，就会报 require not defineed 错误，执行 js 没有问题。

**Comment by Nihiue** [comment]
这个demo仅适用于非打包的场景，如果有webpack的刚需可以看看 bytenode 的解决方案 https://github.com/herberttn/bytenode-webpack-plugin

**Comment by iamluodong** [comment]
好的
